### ISSUE TITLE
'NTM' object has no attribute '_max_length'

### ISSUE THREAD

**Issue by linamede** [carpedm20/NTM-tensorflow#20]
Trying to train the model, it begins well but after a while it shows the error
 'NTM' object has no attribute '_max_length'

 [*] Building a NTM model
Percent: [####################] 100.00% Finished.
 [*] Building a loss model for seq_length 1
 [*] Building a loss model for seq_length 2
 [*] Building a loss model for seq_length 3
 [*] Building a loss model for seq_length 4
 [*] Building a loss model for seq_length 5
 [*] Building a loss model for seq_length 6
 [*] Building a loss model for seq_length 7
 [*] Building a loss model for seq_length 8
 [*] Building a loss model for seq_length 9
 [*] Building a loss model for seq_length 10
 [*] Build a NTM model finished
 [*] Initialize all variables
 [*] Initialization finished
 [*] Reading checkpoints...
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 55, in main
    task.train(ntm, FLAGS, sess)
  File "/home/lina/deep_learning_frameworks/NTM-tensorflow/tasks/copy.py", line 73, in train
    ntm.load(config.checkpoint_dir, config.task, strict=config.continue_train is True)
  File "/home/lina/deep_learning_frameworks/NTM-tensorflow/ntm.py", line 260, in load
    task_dir = "%s_%s" % (task_name, self._max_length)
AttributeError: 'NTM' object has no attribute '_max_length'

**Comment by ruizhaogit** [comment]
I have the same error. Does Anyone get a clue?

**Comment by carpedm20** [comment]
Fixed with 3ebe24a620e3ea8f55078b374b9396b4f02753dd.
