### ISSUE TITLE
Typo in M_erases for multiple heads

### ISSUE THREAD

**Issue by tristandeleu** [carpedm20/NTM-tensorflow#3]
There is a typo in `M_erases` in the case of multiple heads here:
https://github.com/carpedm20/NTM-tensorflow/blob/master/ntm_cell.py#L203-L204
It should be

``` python
M_erases.append(tf.ones([self.mem_size, self.mem_dim]) \
                - outer_product(write_w_idx, erase_idx))
```

**Comment by carpedm20** [comment]
@tristandeleu Thanks! I fixed the code
