### ISSUE TITLE
TypeError: sequence_loss() ...

### ISSUE THREAD

**Issue by frrp** [carpedm20/NTM-tensorflow#4]
When trying to run
$ python main.py --task copy --is_train True
or
$ python main.py --task copy --test_max_length 10

I am getting this TypeError in 'Building a loss model for seq_length' part:

File "/.../NTM-tensorflow/ntm.py", line 139, in build_model
    binary_cross_entropy_with_logits)
TypeError: sequence_loss() got an unexpected keyword argument 'num_decoder_symbols'

I am using python 2.7 in virtual environment.

**Comment by Seanny123** [comment]
Commenting out the argument worked for me.
