### ISSUE TITLE
report a bug with fix solution

### ISSUE THREAD

**Issue by SeekPoint** [carpedm20/NTM-tensorflow#7]
envy@ub1404:~/os_pri/github/NTM-tensorflow$ python main.py --task copy --is_train True
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
{'checkpoint_dir': 'checkpoint',
 'controller_layer_size': 1,
 'epoch': 100000,
 'input_dim': 10,
 'is_train': True,
 'max_length': 10,
 'min_length': 1,
 'output_dim': 10,
 'read_head_size': 1,
 'task': 'copy',
 'test_max_length': 120,
 'write_head_size': 1}
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.55GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I sue the diff like:

I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 

envy@ub1404:~/os_pri/github/NTM-tensorflow$ git diff
diff --git a/ntm.py b/ntm.py
index 595345d..18d512b 100644
--- a/ntm.py
+++ b/ntm.py
@@ -147,7 +147,7 @@ class NTM(object):

```
                 grads = []
                 for grad in tf.gradients(loss, self.params):
```
-                        if grad:
-                        if grad is not None:
                           grads.append(tf.clip_by_value(grad,
                                                         self.min_grad,
                                                         self.max_grad))
  envy@ub1404:~/os_pri/github/NTM-tensorflow$ gi

otherwise it report:

I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
 [_] Building a NTM model
Percent: [####################] 100.00% Finished.
 [_] Building a loss model for seq_length 1
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 27, in main
    cell, ntm = copy_train(FLAGS, sess)
  File "/home/envy/os_pri/github/NTM-tensorflow/tasks/copy.py", line 72, in copy_train
    ntm = NTM(cell, sess, config.min_length, config.max_length)
  File "/home/envy/os_pri/github/NTM-tensorflow/ntm.py", line 82, in **init**
    self.build_model(forward_only)
  File "/home/envy/os_pri/github/NTM-tensorflow/ntm.py", line 150, in build_model
    if grad:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 475, in **nonzero**
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.
envy@ub1404:~/os_pri/github/NTM-tensorflow$

**Comment by ghost** [comment]
Same problem here, the `if grad is not None` fix works for me as well.

**Comment by carpedm20** [comment]
@fracting thanks. I fix the code.

**Comment by ghost** [comment]
Nice, thanks!
