### ISSUE TITLE
it  stuck at ...cannot done

### ISSUE THREAD

**Issue by SeekPoint** [carpedm20/NTM-tensorflow#8]
envy@ub1404:~/os_pri/github/NTM-tensorflow$ python main.py --task copy --is_train True
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
{'checkpoint_dir': 'checkpoint',
 'controller_layer_size': 1,
 'epoch': 100000,
 'input_dim': 10,
 'is_train': True,
 'max_length': 10,
 'min_length': 1,
 'output_dim': 10,
 'read_head_size': 1,
 'task': 'copy',
 'test_max_length': 120,
 'write_head_size': 1}
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.56GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
 [_] Building a NTM model
Percent: [####################] 100.00% Finished.
 [_] Building a loss model for seq_length 1
 [_] Building a loss model for seq_length 2
 [_] Building a loss model for seq_length 3
 [_] Building a loss model for seq_length 4
 [_] Building a loss model for seq_length 5
 [_] Building a loss model for seq_length 6
 [_] Building a loss model for seq_length 7
 [_] Building a loss model for seq_length 8
 [_] Building a loss model for seq_length 9
 [_] Building a loss model for seq_length 10
 [_] Build a NTM model finished
 [_] Initialize all variables
 [_] Initialization finished
[    0]  4: 53.60 (618.3s)
[    5]  1: 13.75 (711.4s)
[   10]  4: 52.69 (711.8s)
[   15]  6: 79.43 (742.8s)
[   20]  1: 14.03 (757.4s)

.....................................................

[ 4775]  8: 0.00 (28215.3s)
[ 4780]  4: 0.00 (28216.3s)
[ 4785]  2: 0.00 (28216.9s)
[ 4790]  9: 0.00 (28218.1s)
[ 4795]  5: 0.00 (28218.9s)

**Comment by carpedm20** [comment]
What do you mean by stuck? I think the training starts well and it will end when it reach max epoch where `100000` is a default value.

**Comment by pasxalinamed** [comment]
Executing the original code, in my case it stucks earlier giving this output

python main.py --task copy --is_train True
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
{'checkpoint_dir': 'checkpoint',
 'controller_layer_size': 1,
 'epoch': 100000,
 'input_dim': 10,
 'is_train': True,
 'max_length': 10,
 'min_length': 1,
 'output_dim': 10,
 'read_head_size': 1,
 'task': 'copy',
 'test_max_length': 120,
 'write_head_size': 1}
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:03:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x2814190
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 12.00GiB
Free memory: 11.82GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
 [*] Building a NTM model
Percent: [####################] 100.00% Finished.
 [*] Building a loss model for seq_length 1
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 50, in main
    cell, ntm = create_ntm(FLAGS, sess)
  File "main.py", line 35, in create_ntm
    test_max_length=FLAGS.test_max_length, **ntm_args)
  File "/home/lina/deep_learning_frameworks/NTM-tensorflow-master/ntm.py", line 82, in __init__
    self.build_model(forward_only)
  File "/home/lina/deep_learning_frameworks/NTM-tensorflow-master/ntm.py", line 138, in build_model
    binary_cross_entropy_with_logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 969, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 933, in sequence_loss_by_example
    crossent = softmax_loss_function(logit, target)
  File "/home/lina/deep_learning_frameworks/NTM-tensorflow-master/ops.py", line 217, in binary_cross_entropy_with_logits
    with ops.name_scope(name, "bce_loss", [logits, targets]) as name:
TypeError: name_scope() takes exactly 1 argument (3 given)

**Comment by lnmed** [comment]
In my case it stucks earlier and gives an output like this


python main.py --task copy --is_train True
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
{'checkpoint_dir': 'checkpoint',
 'controller_layer_size': 1,
 'epoch': 100000,
 'input_dim': 10,
 'is_train': True,
 'max_length': 10,
 'min_length': 1,
 'output_dim': 10,
 'read_head_size': 1,
 'task': 'copy',
 'test_max_length': 120,
 'write_head_size': 1}
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:03:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x2814190
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 12.00GiB
Free memory: 11.82GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
 [*] Building a NTM model
Percent: [####################] 100.00% Finished.
 [*] Building a loss model for seq_length 1
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 50, in main
    cell, ntm = create_ntm(FLAGS, sess)
  File "main.py", line 35, in create_ntm
    test_max_length=FLAGS.test_max_length, **ntm_args)
  File "/home/lnmed/deep_learning_frameworks/NTM-tensorflow-master/ntm.py", line 82, in __init__
    self.build_model(forward_only)
  File "/home/lnmed/deep_learning_frameworks/NTM-tensorflow-master/ntm.py", line 138, in build_model
    binary_cross_entropy_with_logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 969, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py", line 933, in sequence_loss_by_example
    crossent = softmax_loss_function(logit, target)
  File "/home/lnmed/deep_learning_frameworks/NTM-tensorflow-master/ops.py", line 217, in binary_cross_entropy_with_logits
    with ops.name_scope(name, "bce_loss", [logits, targets]) as name:
TypeError: name_scope() takes exactly 1 argument (3 given)
